article/urls.py
# 引入path
from django.urls import path

# 引入views.py
from . import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    # path函数将url映射到视图
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    
]

blog/urls.py
from cgitb import handler
from django.contrib import admin
from django.urls import path, include
from article import views
# 新引入的模块
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 首页
    path('', include('index.urls', namespace='index')),
    #管理页面
    path('admin/', admin.site.urls),
    # 文章
    path('article/', include('article.urls', namespace='article')),
    # 用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # 评论
    path('comment/', include('comment.urls', namespace='comment')),
    # 项目
    path('project/', include('project.urls', namespace='project')),
    # 自己介绍
    path('myself/', include('myself.urls', namespace='myself')),
    # 经历
    path('life/', include('life.urls', namespace='life')),
    # 学术成果
    path('scholar/', include('scholar.urls', namespace='scholar')),
]
#添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.page_not_found
handler500 = views.page_error

life/urls.py
# 引入path
from django.urls import path

# 引入views.py
from . import views

# 正在部署的应用的名称
app_name = 'life'

urlpatterns = [
    # path函数将url映射到视图
    path('life-list/', views.life_list, name='life_list'),
    # 文章详情
    path('life-detail/<int:id>/', views.life_detail, name='life_detail'),
    
]

project/urls.py
# 引入path
from django.urls import path

# 引入views.py
from . import views

# 正在部署的应用的名称
app_name = 'project'

urlpatterns = [
    # path函数将url映射到视图
    path('project-list/', views.project_list, name='project_list'),
    # 文章详情
    path('project-detail/<int:id>/', views.project_detail, name='project_detail'),
    
]

scholar/urls.py
# 引入path
from django.urls import path

# 引入views.py
from . import views

# 正在部署的应用的名称
app_name = 'scholar'

urlpatterns = [
    # path函数将url映射到视图
    path('scholar-list/', views.scholar_list, name='scholar_list'),
    # 文章详情
    path('scholar-detail/<int:id>/', views.scholar_detail, name='scholar_detail'),
]

templates/back_to_top_func.html
<!-- 参考了 鹦鹉 的代码，在此致谢 -->
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->

<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
<!-- 
    载入静态文件
    使用 Django 3 学习的读者改为 {% load static %}
-->
{% load static %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>二两酥肉的博客</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.6.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/pygments.css' %}">
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- body位置 -->
    {% block content %}
    {% endblock content %}

    {% comment %} <div id="wrapper">
        {% block content %}{% endblock content %}
        <div id="push"></div>
    </div> {% endcomment %}
    {% comment %} 
    <!-- 引入注脚 -->
    {% include 'footer.html' %}  
    {% endcomment %}

    <!-- 增加样式 -->
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            width:100%;
            float:left;
            min-height: 94%;
            {% comment %} height:100%; {% endcomment %}
        }
    </style>

    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js"></script>
    <link 
      rel="stylesheet" 
      href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css"
    >
    <!-- 
        popper.js 采用 cdn 远程引入，意思是你不需要把它下载到本地。
        在实际的开发中推荐静态文件尽量都使用 cdn 的形式。 
        教程采用本地引入是为了让读者了解静态文件本地部署的流程。
    -->
    
    <script src="https://cdn.bootcdn.net/ajax/libs/popper.js/2.11.4/cjs/popper.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/popper.js/2.11.4/cjs/enums.min.js"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.6.1/js/bootstrap.min.js"></script>
    <!-- 在jquery后面引入 -->
    {% comment %} {% include 'back_to_top_func.html' %} {% endcomment %}
    
</body>

</html>

templates/footer.html
{% load static %}
<!-- Footer -->

<div>
    <br><br><br>
</div> 
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white">bamboosir920</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏 -->
<nav id="header" class="navbar navbar-expand-lg navbar-dark bg-dark">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <div class="headers">
  
      <!-- 导航栏商标 -->
      <div class="index">
        <a class="navbar-brand" href="../../../" id="index_a">我的博客</a>
      </div>
      <!-- 导航入口 -->

      <div class="link">
        <div class="link_box">
          <a class="link_box_a" href="{% url 'article:article_list' %}">文章</a>
        </div>
        <div class="link_box">
          <a class="link_box_a" href="{% url 'project:project_list' %}">项目</a>
        </div>
        <div class="link_box">
          <a class="link_box_a" href="{% url 'scholar:scholar_list' %}">论文</a>
        </div>
        <div class="link_box" id="link_box_1">
          <a class="link_box_a" href="{% url 'life:life_list' %}">我的经历</a>
        </div>
        <div class="link_box">
          <a class="link_box_a" href="/myself">关于我</a>
        </div>
       
          <ul class="navbar-nav">
            <!-- 条目 -->
            {% comment %} <li class="nav-item">
              <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
            </li> {% endcomment %}
            {% comment %} <li class="nav-item">
              <a class="nav-link" href="{% url 'project:project_list' %}">项目</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'scholar:scholar_list' %}">论文</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'life:life_list' %}">我的经历</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/myself">关于我</a>
            </li> {% endcomment %}
            <!-- Django的 if 模板语句 -->
            {% if user.is_authenticated %}
            <!-- 如果用户已经登录，则显示用户名下拉框 -->
            <li class="nav-item dropdown">
                <a class="link_box_a dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
                  <a class="dropdown-item" href='{% url "userprofile:logout" %}'>退出登录</a>
                </div>
            </li>
            <!-- 如果用户未登录，则显示 “登录” -->
            {% else %}
            <li class="nav-item">
                <a class="link_box_a" href="{% url 'userprofile:login' %}">登录</a>
            </li>                    
            <!-- if 语句在这里结束 -->
            {% endif %}
          </ul>

      </div>
  
    </div>
  </nav>