article/urls.py
# 引入path
from django.urls import path

# 引入views.py
from . import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    # path函数将url映射到视图
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    
]

blog/urls.py
from cgitb import handler
from django.contrib import admin
from django.urls import path, include
from article import views
# 新引入的模块
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 首页
    path('', include('index.urls', namespace='index')),
    #管理页面
    path('admin/', admin.site.urls),
    # 文章
    path('article/', include('article.urls', namespace='article')),
    # 用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # 评论
    path('comment/', include('comment.urls', namespace='comment')),
    # 项目
    path('project/', include('project.urls', namespace='project')),
    # 自己介绍
    path('myself/', include('myself.urls', namespace='myself')),
    # 经历
    path('life/', include('life.urls', namespace='life')),
    # 学术成果
    path('scholar/', include('scholar.urls', namespace='scholar')),
]
#添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.page_not_found
handler500 = views.page_error

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
     # 项目栏发表评论
    path('post-project-comment/<int:project_id>/', views.post_project_comment, name='post_project_comment'),
    # 项目栏发表评论
    path('post-life-comment/<int:life_id>/', views.post_life_comment, name='post_life_comment'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.user_register, name='register'),
    # 用户信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
# Create your models here.
from django.db import models
# 导入内建的User模型。
from django.contrib.auth.models import User
# timezone 用于处理时间相关事务。
from django.utils import timezone
#路由重定向
from django.urls import reverse
# Django-taggit
from taggit.managers import TaggableManager
# 记得导入！
from PIL import Image
# 博客文章数据模型
class ArticleColumn(models.Model):
    """
    栏目的 Model
    """
    # 栏目标题
    title = models.CharField(max_length=100, blank=True)
    # 创建时间
    created = models.DateTimeField(default=timezone.now)
    

    def __str__(self):
        return self.title
    
class ArticlePost(models.Model):
    # 文章作者。参数 on_delete 用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)
    # 文章正文。保存大量文本使用 TextField
    body = models.TextField()
    # 文章创建时间。参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)
    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)
    # 文章标签
    tags = TaggableManager(blank=True)
    #阅读量
    total_views = models.PositiveIntegerField(default=0)
    
    '''
    图片存储
    '''
    # 文章标题图
    # 原来为本地图片，在v0.6以后改为网络存储
    # avatar = models.ImageField(upload_to='article/%Y%m%d/', blank=True)
    avatar = models.URLField(default="https://s1.ax1x.com/2022/04/11/LEjUYV.jpg")
     # 保存时处理图片
    # def save(self, *args, **kwargs):
    #     # 调用原有的 save() 的功能
    #     article = super(ArticlePost, self).save(*args, **kwargs)
    #     # 固定宽度缩放图片大小
    #     if self.avatar and not kwargs.get('update_fields'):
    #         image = Image.open(self.avatar)
    #         (x, y) = image.size
    #         new_x = 400
    #         new_y = int(new_x * (y / x))
    #         resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
    #         resized_image.save(self.avatar.path)

    #     return article
    # 内部类 class Meta 用于给 model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)
    
    # 文章栏目的 “一对多” 外键
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )
    
    # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
    def __str__(self):
        # return self.title 将文章标题返回
        return self.title
    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

article/views.py
from django.shortcuts import render

# 导入数据模型ArticlePost
from .models import ArticlePost
# 引入markdown模块
import markdown
# 引入分页模块
from django.core.paginator import Paginator
# 引入 Q 对象
from django.db.models import Q
# 记得导入！
from PIL import Image
from django.shortcuts import get_object_or_404
from comment.models import Comment
from index.models import SeriesBg

# 文章列表
def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')
    
    #背景图
    seriesbg_list = SeriesBg.objects.all()
    seriesbg1=seriesbg_list[0]
    
    # 初始化查询集
    # 根据GET请求中查询条件
    # 返回不同排序的对象数组
    # 取出所有博客文章
    article_list = ArticlePost.objects.all()

    # 搜索查询集
    if search:
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''
        
    # 栏目查询集
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

    # 标签查询集
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    # 查询集排序
    if order == 'total_views':
        article_list = article_list.order_by('-total_views')
        
    # 每页显示 6 篇文章
    paginator = Paginator(article_list, 6)
    # 获取 url 中的页码
    page = request.GET.get('page')
    # 将导航对象相应的页码内容返回给 articles
    articles = paginator.get_page(page)
    
    # 需要传递给模板（templates）的对象
    context = {
        'articles': articles,
        'order': order,
        'search': search,
        'column': column,
        'tag': tag,
        'seriesbg1':seriesbg1,
    }
    # render函数：载入模板，并返回context对象
    return render(request, 'article/list.html', context)

# 文章详情
def article_detail(request, id):
    # 取出相应的文章
    # article = ArticlePost.objects.get(id=id)
    article = get_object_or_404(ArticlePost, id=id)
    # 取出文章评论
    comments = Comment.objects.filter(article=id)
    #将markdown语法渲染成html样式
    md = markdown.Markdown(
        extensions=[
        'markdown.extensions.extra',
         # 语法高亮扩展
        'markdown.extensions.codehilite',
        # 目录扩展
        'markdown.extensions.toc',
        ],
        safe_mode=True,
        enable_attributes=False
    )
    article.body = md.convert(article.body)
    
    # 浏览量 +1
    article.total_views += 1
    article.save(update_fields=['total_views'])
    
    # 需要传递给模板的对象
    context = { 'article': article, 'toc': md.toc, 'comments': comments }
    # 载入模板，并返回context对象
    return render(request, 'article/detail.html', context)

# 404
def page_error(request):
    return render(request, '404.html', status=404)


# 500
def page_not_found(request, exception):
    return render(request, '404.html', status=500)

templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <!-- 标题及作者 -->
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="col-12 alert alert-success">
                <div>
                    作者：{{ article.author }}
                </div>
                <div>
                    浏览：{{ article.total_views }}
                </div>
            </div>
            <!-- 文章正文 -->
            <div class="col-12">
                <p>{{ article.body|safe}}</p>
            </div>
            <!-- 发表评论 -->
            <hr>
            {% if user.is_authenticated %}
            <div>
                <form 
                    action="{% url 'comment:post_comment' article.id %}" 
                    method="POST"
                >
                {% csrf_token %}
                    <div class="form-group">
                        <label for="body">
                            <strong>
                                我也要发言：
                            </strong>
                        </label>
                        <textarea 
                            type="text" 
                            class="form-control" 
                            id="body" 
                            name="body" 
                            rows="2"></textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary ">发送</button>                    
                </form>
            </div>
            <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                </h5>
                <br>
            {% endif %}
             <!-- 显示评论 -->
            <h4>共有{{ comments.count }}条评论</h4>
            <div>
                {% for comment in comments %}
                    <hr>
                    <p>
                        <strong style="color: pink">
                            {{ comment.user }}
                        </strong> 于 
                        <span style="color: green">
                            {{ comment.created|date:"Y-m-d H:i:s" }}
                        </span> 时说：
                    </p>
                    <pre style="font-family: inherit; font-size: 1em;">
                    {{ comment.body }}</pre>
                {% endfor %}
            </div>
        </div>
        <!-- 目录 -->
        {% comment %} <div class="col-3 mt-4">
            <h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div> {% endcomment %}
    </div>
</div>

{% endblock content %}

templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<link rel="stylesheet" href="{% static 'css/article_list.css' %}">
<style>
    body{
      background-image: url({{ seriesbg1.avatar }});
    }

</style>
<div class="body_box">
<div class="body_head_box">
  <!-- 新增，搜索栏 -->
  <!-- 由于暂时没找到合适的美观替换，暂时取消掉排序 -->
  {% comment %} 
  <div class="body_head_select_box" >
      <div class="body_head_select_order_box"id="body_head_select_order_box_1">
        <a href="{% url 'article:article_list' %}?search={{ search }}&column={{ column }}&tag={{ tag }}">
          最新
        </a>
      </div>
      <div class="body_head_select_order_box" id="body_head_select_order_box_2">
        <a href="{% url 'article:article_list' %}?search={{ search }}&column={{ column }}&tag={{ tag }}">
          最热
        </a>
      </div>
      <div  class="body_head_select_none_box">
      </div>
      <div class="body_head_select_search_box">
          <form class="form-inline">
            <label class="sr-only">content</label>
            <input type="text" 
                class="form-control mb-2 mr-sm-2" 
                name="search" 
                placeholder="搜索文章..." 
                required
            >
            <button class="body_head_select_search_btn">~</button>
          </form>
        </div> 
      </div> 
    <!-- 新增，搜索提示语 -->
  {% if search %}
      {% if articles %}
          <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
          <hr>        
      {% else %}
          <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
          <hr>
      {% endif %}
    {% endif %} 
  {% endcomment %}
</div>

<div class="body_main_box">
    {% for article in articles %}
        <a class="card" href="{% url 'article:article_detail' article.id %}">
          <div class="front" 
          {% if article.avatar %}
            style="background-image: url({{ article.avatar }});" 
          {% endif %}
          >
            <p>{{ article.title }}</p>
          </div>
          <div class="back">
            <div>
              {% comment %} 神奇的bug {% endcomment %}
                {% comment %} {% if article.column %}
                <button type="button" class="btn btn-sm mb-2">
                    {{ article.column }}
                </button>
                {% endif %}
                {% for tag in article.tags.all %}
                <a href="{% url 'article:article_list' %}?tag={{ tag }}"class="badge badge-secondary">
                    {{ tag }}
                </a>
                {% endfor %} {% endcomment %}
                
                {{ article.body|slice:'100' }}...

                <!-- 注脚 -->
              <p>
                <!-- 附加信息，增加了图标 -->
                <span>
                    <i class="fas fa-eye" style="color: lightskyblue;"></i>
                    {{ article.total_views }}&nbsp;&nbsp;&nbsp;
                </span>
                <span>
                    <i class="fas fa-comments" style="color: yellowgreen;"></i>
                    <!-- 修改为评论的计数 -->
                    {{ article.comments.count }}&nbsp;&nbsp;&nbsp;
                </span>
                <span>
                    <i class="fas fa-clock" style="color: pink;"></i>
                    {{ article.created|date:'Y-m-d' }}
                </span>
              </p>
              {% comment %} <button class="button">Click Here</button> {% endcomment %}
            </div>
          </div>
        </a>
    {% endfor %}
</div>

<!-- 页码导航 -->
<div class="body_footer_box">
    <div class="m-auto">
        <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if articles.has_previous %}
            <div class="step_link_box" id="step_link_box_1">
              <a href="?page=1&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" ><1</a>
            </div>
            <div  class="step_link_box">
              <span style="font-size:20px;font-weight:500">...</span>
            </div>
            <div  class="step_link_box" id="step_link_box_2">
              <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}">
                    {{ articles.previous_page_number }}
              </a>
            </div>
            {% endif %}

            <!-- 当前页面 -->
            <div class="step_link_box" id="step_link_box_3">
            <span  class="step_link_box">
                {{ articles.number }}
            </span>
          </div>

            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if articles.has_next %}
            <div class="step_link_box" id="step_link_box_1">
              <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}">{{ articles.next_page_number }}</a>
            </div>
            <div  class="step_link_box">
              <span style="font-size:20px;font-weight:500">...</span>
            </div>
            <div  class="step_link_box" id="step_link_box_2">
              <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}">{{ articles.paginator.num_pages }} ></a>
            </div>
            {% endif %}
        </span>
    </div>
</div>
</div>

{% endblock content %}